secureFtp:
  host: 192.168.133.130
  port: 22
  userName: arun
  password: test
  allowUnknownKeys: true
  
  
sftp:
  autoconfigure:
    enabled: true
    
folder:
  data: '{  "002" : {"Tag" : "Location1","NoTag" : "Location2"} , 
            "004-008" : {"NoTag" : "Location"},
            "AMLO" : {"NoTag" : "Location"}
         }'